#!/usr/bin/env perl
use Dzpl
    name => 'Text-Clip',
    version => '0.0014',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        Any::Moose

        [Test]
        Test::Most
    /;
;

{ plugin '@ROKR::Basic' }
